# Generated by Django 5.2.11 on 2026-02-18 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.BinaryField(help_text='512-D float32 centroid embedding (2048 bytes)')),
                ('embedding_dim', models.PositiveIntegerField(default=512)),
                ('num_samples', models.PositiveIntegerField(default=0, help_text='Number of face samples used to compute centroid')),
                ('intra_sim_mean', models.FloatField(blank=True, help_text='Mean intra-person cosine similarity (quality metric)', null=True)),
                ('intra_sim_min', models.FloatField(blank=True, null=True)),
                ('intra_sim_std', models.FloatField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, help_text='Path to best reference face crop', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__roll_no'],
            },
        ),
    ]
