# Generated by Django 5.2.11 on 2026-02-18 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.OneToOneField(blank=True, help_text='Head of Department', limit_choices_to={'role': 'hod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectteacher',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'hod']}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('department', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectteacher',
            unique_together={('subject',)},
        ),
    ]
